### ISSUE TITLE
 API call to drive.files.copy failed with error

### ISSUE THREAD

**Issue by OgnistyPoland** [ericyd/gdrive-copy#111] opened 2019-05-30 16:38 UTC
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
I think yes
### My problem:
Error:  API call to drive.files.copy failed with error: User rate limit exceeded. File: GDriveService (Copy Folder). Line: 93

https://i.imgur.com/TKR0TOL.png
### Specify your

* operating system: Windows 10
* browser: Chrome

**Comment by ericyd** [comment] 2019-06-02 18:53
duplicate of #86

**Closed by ericyd** 2019-06-02 18:53 UTC
