### ISSUE TITLE
Option to change limit of quota?

### ISSUE THREAD

**Issue by theheartbenvn** [ericyd/gdrive-copy#170] opened 2020-08-13 04:15 UTC
Hi, i just came to know that the script stops after 90 minutes of running. Though what you said is true - about the runtime, but it only applies for consumer account, not Business or School account. It has 6 hours limit instead.

So i was wondering if there's anyway to change the time limit of the script to 6 hours, other than having to restart the script every 90 minutes? Thanks in advance.

**Comment by ericyd** [comment] 2020-08-13 05:01
Duplicate of #72 

You missed the [oath of good faith](https://github.com/ericyd/gdrive-copy/blob/main/issue_template.md#oath-of-good-faith) in the issue template 😉

**Closed by ericyd** 2020-08-13 05:01 UTC

**Comment by theheartbenvn** [comment] 2020-08-13 05:09
Ah, okay, thank you. Sorry for the trouble.
