### ISSUE TITLE
Empty JSON string - application (Copy Folder) - 762 status - 

### ISSUE THREAD

**Issue by edotrajan** [ericyd/gdrive-copy#8] opened 2017-02-10 00:54 UTC
even after allowing hours after pausing and resuming it still shows same response.

help would be appreciated

![capture](https://cloud.githubusercontent.com/assets/8685672/22809576/70242894-ef59-11e6-8921-3260ae0c0e72.PNG)

**Comment by ericyd** [comment] 2017-02-12 00:52
The error is being called in the loadProperties() method, which is used to initialize the program with the data from the previous run.

This error would occur if the program failed to save data correctly when it was pausing, or if you accidentally deleted the configuration file (titled "DO NOT DELETE").

I would recommend restarting the copy. Either the configuration was corrupted somehow or it is no longer available, but either way there is no recovery process in place for copies that are partially complete but no longer have the configuration data.

**Comment by ericyd** [comment] 2017-12-31 01:10
closing as I've never been able to reproduce this behavior and it has never been reported since original post

**Closed by ericyd** 2017-12-31 01:10 UTC
