### ISSUE TITLE
Problem with not english characters in filename

### ISSUE THREAD

**Issue by hevesitibor** [ericyd/gdrive-copy#49] opened 2018-05-31 15:07 UTC
### Are you requesting a feature or reporting a bug?
The file names or folders wiht non english characters are not transferred correctly 

### If reporting a bug, is there already an issue open for this same bug?
no

### What is the current behavior?
á, é, ő, ü ... are changed for other charactrs

### What is the expected behavior?
kepp this characters in names after copy.

### Specify your

* operating system: windows 10
* browser: chrome

**Comment by ericyd** [comment] 2018-12-10 06:09
Closing as unable to reproduce

**Closed by ericyd** 2018-12-10 06:09 UTC
