### ISSUE TITLE
Error:  API call to drive.files.copy failed with error: File not found: . File: GDriveService (Copy Folder). Line: 93

### ISSUE THREAD

**Issue by iamvpk** [ericyd/gdrive-copy#122] opened 2019-08-29 15:57 UTC
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
No
### What is the current behavior?
Error:  API call to drive.files.copy failed with error: File not found: . File: GDriveService (Copy Folder). Line: 93
### Specify your

* operating system: Windows 10 Pro x64 Latest Build
* browser: Google Chrome

**Comment by ericyd** [comment] 2019-09-01 19:38
Duplicate of #54

**Closed by ericyd** 2019-09-01 19:38 UTC
