### ISSUE TITLE
API call to drive.files.insert failed with error: File not found:

### ISSUE THREAD

**Issue by jomergallano** [ericyd/gdrive-copy#142] opened 2020-01-03 06:44 UTC
### Are you requesting a feature or reporting a bug?
**_Error: "API call to drive.files.insert failed with error: File not found:"_**

### What is the current behavior?
Drive from Domain Drive
### Specify your

* operating system: Windows 10
* browser: Chrome

**Comment by ericyd** [comment] 2020-01-03 15:50
Could you elaborate on what you mean by
> Drive from Domain Drive

**Comment by ericyd** [comment] 2020-01-20 00:05
Dupe of #138

**Closed by ericyd** 2020-01-20 00:05 UTC
