### ISSUE TITLE
Error ocurred plz help

### ISSUE THREAD

**Issue by edok13** [ericyd/gdrive-copy#23] opened 2017-05-01 23:30 UTC
### Are you requesting a feature or reporting a bug?
i tried copying a lot of files & subfolder by your copy a google drive folder apps but there are some errors so i can't copy them

when first trial, part of them copied successly and another them can't copied(and unfortunately i have no copy log i erased them). and then i tried sometimes, but now i can copied only subfolder except any files

i check that copy folder log, and there are some errors.

error code(?) : Error, GoogleJsonResponseException: User rate limit exceeded

plz help me

### Specify your

* operating system: Win10 64bit
* browser: Chrome

**Comment by ericyd** [comment] 2017-05-11 19:42
Duplicate of #6 .

**Closed by ericyd** 2017-05-11 19:42 UTC
