### ISSUE TITLE
I use Gsuite edu but why stop in 90 min?

### ISSUE THREAD

**Issue by Dhanamerdeka** [ericyd/gdrive-copy#148] opened 2020-02-16 10:46 UTC
I have Gsuite EDU and using this script
But why script stopped after 90min?
script should stop after run 3hr
(https://developers.google.com/apps-script/guides/services/quotas)

**Comment by ericyd** [comment] 2020-02-17 18:10
Duplicate of #144

**Closed by ericyd** 2020-02-17 18:10 UTC
