### ISSUE TITLE
Progress Status as "working" but on hold for almost 1 hour

### ISSUE THREAD

**Issue by andrealho** [ericyd/gdrive-copy#56] opened 2018-10-10 13:00 UTC
### Are you requesting a feature or reporting a bug?

Reporting a bug 

### If reporting a bug, is there already an issue open for this same bug?

Doesn't seem like it.

### What is the current behavior?

Started transfer of folder a few hours ago, got a "Paused due to Google quota limits - transfer will resume in 1-2 minutes" but never resumed. Log status ok 'working' for over 45 minutes but no file is processed nor more emails are received.

### What is the expected behavior?

Hopefully process would be concluded.

### How would you reproduce the current behavior (if this is a bug)?

Not sure, only if I re-triggered the process but afraid it might mess it up more.

### Specify your

* operating system: macOS High Sierra
* browser: Safari

**Comment by ericyd** [comment] 2018-10-10 14:33
You'll want to use the "Resume" feature in the app. Unfortunately this happens from time to time.

---- On Wed, 10 Oct 2018 06:00:55 -0700  notifications@github.com wrote ----

Are you requesting a feature or reporting a bug?
Reporting a bug

If reporting a bug, is there already an issue open for this same bug?
Doesn't seem like it.

What is the current behavior?
Started transfer of folder a few hours ago, got a "Paused due to Google quota limits - transfer will resume in 1-2 minutes" but never resumed. Log status ok 'working' for over 45 minutes but no file is processed nor more emails are received.

What is the expected behavior?
Hopefully process would be concluded.

How would you reproduce the current behavior (if this is a bug)?
Not sure, only if I re-triggered the process but afraid it might mess it up more.

Specify your
operating system: macOS High Sierra
browser: Safari

**Comment by andrealho** [comment] 2018-10-10 15:05
@ericyd I tried it but once I click resume it leads to a blank page and it's still stuck.

**Comment by ericyd** [comment] 2018-12-03 00:02
Can you clarify what you mean by "leads to a blank page"? If the app is crashing that is an issue.

**Comment by ericyd** [comment] 2018-12-03 01:00
I appreciate the extra info. I've never seen the app crash but I'll do some testing in Safari soon to see if I can reproduce.

Did the app modify the permissions of the original files? I'm sorry to hear that the permissions of the new copy were not correct, but the original files should never be modified.

**Comment by andrealho** [comment] 2018-12-03 05:48
I'm sorry but can't recall more details, this was almost two months ago...

**Comment by ericyd** [comment] 2018-12-04 01:39
I can't reproduce the Safari issue at the moment. I'm going to leave this open for now in case other people are experiencing the script stopping abruptly.

**Comment by ericyd** [comment] 2019-03-16 19:09
Going to close this as no new reports have surfaced and I am not able to reproduce the original issue

**Closed by ericyd** 2019-03-16 19:09 UTC
