### ISSUE TITLE
Subfolder permissions not copied

### ISSUE THREAD

**Issue by QASICross** [ericyd/gdrive-copy#39] opened 2018-02-19 19:46 UTC
### Specify your

* operating system:  Windows 7 Professional
* browser:  Google Chrome

**Comment by ericyd** [comment] 2018-03-11 20:07
Is this issue persistent or was it a one-time issue? I am not able to reproduce.

**Comment by QASICross** [comment] 2018-03-12 10:45
I am copying a folder for time sheets.  The folder is shared with
everyone.  Inside the folder are the individual's time sheets that are only
shared with the individuals.  When I copy the folder and ask it to keep
permissions of the original folder it copies everything, but it adds the
permissions of the root folder to all of the individual sheets.  So I have
to go through all of the individual spreadsheets and remove the permissions
of everyone the folder is shared with and just leave the individual the
time sheet belongs to.  It didn't use to do that.  It use to keep all
permissions, both of the root folder and the individual sheets in the
folder, but after an update was put through it doesn't do that anymore,
It's very time consuming for me to go through and re-do the permissions on
all of the individual sheets.  Hopefully, you can get it fixed.  It's a
really nice thing to have...it it works right. :-)  Thanks for your time
and consideration.
Thanks,
Cindy

**Comment by QASICross** [comment] 2018-03-15 01:24
Hi Eric,
I just wanted to thank you for fixing this problem.  I just copied my time
sheets folder and it actually copied all the permissions correctly this
time so you must have fixed it.  This saves me a huge amount of time!
Thanks again,
Cindy

**Comment by ericyd** [comment] 2018-03-15 03:27
Cool! I'll close the issue for now but feel free to comment here again if it starts happening again.

**Closed by ericyd** 2018-03-15 03:27 UTC
