### ISSUE TITLE
Error:  drive.files.copy API 调用失败，错误信息：User rate limit exceeded. File: GDriveService (Copy Folder). 

### ISSUE THREAD

**Issue by Profitter** [ericyd/gdrive-copy#146] opened 2020-02-11 03:03 UTC
Error occured that when copying large files like 4K movie, the copying process stopped and the error log are as above.

**Comment by ericyd** [comment] 2020-02-11 17:45
Duplicate of #82

**Closed by ericyd** 2020-02-11 17:45 UTC
