### ISSUE TITLE
Error: User rate limit exceeded. File: application. Line: 524

### ISSUE THREAD

**Issue by IhToN** [ericyd/gdrive-copy#62] opened 2018-12-02 11:13 UTC
### Are you requesting a feature or reporting a bug?
Bug

### If reporting a bug, is there already an issue open for this same bug?
I couldn't find anything

### What is the current behavior?
``` Error: User rate limit exceeded. File: application. Line: 524 ```
This message appears when I'm trying to copy Big-Size files. Although I'm not using the public macro but one stored on my GSuite Account.

It may be that there is a max-size cap on "Drive.Files.copy"? If that's the case, is there any way to remove it?

* operating system: Win 10
* browser: Chrome

**Comment by ericyd** [comment] 2018-12-02 21:17
This is actually a duplicate of #55 its just a different line number because of the application version. I believe I just need to implement a throttler in the request helper, just haven't had time.

**Closed by ericyd** 2018-12-02 21:17 UTC
