### ISSUE TITLE
Error, GoogleJsonResponseException: User rate limit exceeded

### ISSUE THREAD

**Issue by Qwatuz** [ericyd/gdrive-copy#26] opened 2017-05-11 00:37 UTC
### Are you requesting a feature or reporting a bug?

Bug?

### What is the current behavior?

"Error, GoogleJsonResponseException: User rate limit exceeded"

### What is the expected behavior?

Copy folders

### How would you reproduce the current behavior (if this is a bug)?

Copying large folder seems to stop after a short time.

http://i.imgur.com/njFgg6s.png

### Specify your

* operating system: Win7
* browser: Chrome

**Comment by hthighway** [comment] 2017-05-11 03:05
I am see the same issue
The process seemed to be moving along fine until about the 2900th item, then just a string of
```
User rate limit exceeded
Error, GoogleJsonResponseException: User rate limit exceeded
```

**Comment by cayars** [comment] 2017-05-11 05:12
I see I'm not alone.

User rate limit exceeded
Error, GoogleJsonResponseException: User rate limit exceeded

Is what I'm seeing in the log file as well.

**Comment by ericyd** [comment] 2017-05-11 19:41
Duplicate of #23, which in turn is a duplicate of #6.

**Closed by ericyd** 2017-05-11 19:41 UTC
