### ISSUE TITLE
Allow copying to Team Drives

### ISSUE THREAD

**Issue by GerardBalaoro** [ericyd/gdrive-copy#47] opened 2018-05-13 11:17 UTC
A remarkable feature for GSuite subscribers is the ability to create Team Drives, while this drive can be shared to other Gmail accounts, it does not support moving folders into it. I was hoping this tool will be able to create copies of a folder inside a Team Drive.

**Comment by ericyd** [comment] 2018-05-15 04:19
Thank you for the comment, but going to close because it is a duplicate of [#10](https://github.com/ericyd/gdrive-copy/issues/10). It does seem like it would be a good feature to implement, just not sure when I'll have the time.

**Closed by ericyd** 2018-05-15 04:19 UTC
