### ISSUE TITLE
 User rate limit exceeded

### ISSUE THREAD

**Issue by FosterG4** [ericyd/gdrive-copy#137] opened 2019-11-21 14:58 UTC
### Are you requesting a feature or reporting a bug?
This is bug

### If reporting a bug, is there already an issue open for this same bug?
No

This bug
Error:  API call to drive.files.copy failed with error: User rate limit exceeded. File: GDriveService (Copy Folder). Line: 93

### Specify your

* operating system: Ubuntu 18.04
* browser: Chrome latest

**Comment by ericyd** [comment] 2020-01-20 00:06
dupe of #134

**Closed by ericyd** 2020-01-20 00:06 UTC
